greenhouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: pipeline
      password: pipeline123
      dbname: recruitment
      schema: public
      threads: 4
